/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AccidentsRouteImport } from './routes/accidents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IncidentsIdRouteImport } from './routes/incidents.$id'

const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccidentsRoute = AccidentsRouteImport.update({
  id: '/accidents',
  path: '/accidents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIdRoute = IncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accidents': typeof AccidentsRoute
  '/alerts': typeof AlertsRoute
  '/demo': typeof DemoRoute
  '/heatmap': typeof HeatmapRoute
  '/live': typeof LiveRoute
  '/settings': typeof SettingsRoute
  '/vehicles': typeof VehiclesRoute
  '/violations': typeof ViolationsRoute
  '/incidents/$id': typeof IncidentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accidents': typeof AccidentsRoute
  '/alerts': typeof AlertsRoute
  '/demo': typeof DemoRoute
  '/heatmap': typeof HeatmapRoute
  '/live': typeof LiveRoute
  '/settings': typeof SettingsRoute
  '/vehicles': typeof VehiclesRoute
  '/violations': typeof ViolationsRoute
  '/incidents/$id': typeof IncidentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accidents': typeof AccidentsRoute
  '/alerts': typeof AlertsRoute
  '/demo': typeof DemoRoute
  '/heatmap': typeof HeatmapRoute
  '/live': typeof LiveRoute
  '/settings': typeof SettingsRoute
  '/vehicles': typeof VehiclesRoute
  '/violations': typeof ViolationsRoute
  '/incidents/$id': typeof IncidentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accidents'
    | '/alerts'
    | '/demo'
    | '/heatmap'
    | '/live'
    | '/settings'
    | '/vehicles'
    | '/violations'
    | '/incidents/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accidents'
    | '/alerts'
    | '/demo'
    | '/heatmap'
    | '/live'
    | '/settings'
    | '/vehicles'
    | '/violations'
    | '/incidents/$id'
  id:
    | '__root__'
    | '/'
    | '/accidents'
    | '/alerts'
    | '/demo'
    | '/heatmap'
    | '/live'
    | '/settings'
    | '/vehicles'
    | '/violations'
    | '/incidents/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccidentsRoute: typeof AccidentsRoute
  AlertsRoute: typeof AlertsRoute
  DemoRoute: typeof DemoRoute
  HeatmapRoute: typeof HeatmapRoute
  LiveRoute: typeof LiveRoute
  SettingsRoute: typeof SettingsRoute
  VehiclesRoute: typeof VehiclesRoute
  ViolationsRoute: typeof ViolationsRoute
  IncidentsIdRoute: typeof IncidentsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accidents': {
      id: '/accidents'
      path: '/accidents'
      fullPath: '/accidents'
      preLoaderRoute: typeof AccidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$id': {
      id: '/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof IncidentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccidentsRoute: AccidentsRoute,
  AlertsRoute: AlertsRoute,
  DemoRoute: DemoRoute,
  HeatmapRoute: HeatmapRoute,
  LiveRoute: LiveRoute,
  SettingsRoute: SettingsRoute,
  VehiclesRoute: VehiclesRoute,
  ViolationsRoute: ViolationsRoute,
  IncidentsIdRoute: IncidentsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
